substitutions:
  name: mdtronix-3ch-switch-d63ca7
  friendly_name: MDtronix 3ch Switch
packages:
  MDtronix.3ch-switch: github://mrunmaydarpan/ESPHome-config/3ch-switch.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
