esphome:
  name: test-1

esp8266:
  board: d1_mini
  restore_from_flash: True

preferences:
  flash_write_interval: 5s
logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: "home"
  password: "darkmaster"
  ap: {}
  fast_connect: true
  min_auth_mode: WPA

captive_portal:
web_server:
  version: 3

uart:
  baud_rate: 9600
  rx_pin: D6
  id: uart_id

globals:
  - id: last_update
    type: unsigned long
    restore_value: no
    initial_value: "0"

sensor:
  - platform: a02yyuw
    id: sensor_id
    name: Distance test
    filters:
      - throttle:
          seconds: 1
      - multiply: 0.1
    on_value:
      then:
        - lambda: |-
            id(last_update) = millis();

switch:
  - platform: template
    id: switch_id
    name: switch
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True

interval:
  interval: 5s
  id: check_id
  then:
    - lambda: |-
        unsigned long now = millis();
        if (now - id(last_update) > 5000) 
        {
          ESP_LOGE("CHECK", "Sensor not responding");
        }
