globals:
  - id: dryrun_last_dist
    type: float

  - id: last_dryrun_ts
    type: unsigned long
    initial_value: '0'

binary_sensor:
  - platform: template
    id: dryrun_state_id
    name: DryRun
    device_class: problem
    entity_category: diagnostic

interval:
  - interval: 1s
    id: dryrun_check_timer
    then:
      - if:
          condition:
            and:
              - switch.is_on: dryrun_id
              - switch.is_on: pump_id
          then:
            - lambda: |-
                unsigned long now = millis();
                if(now - id(last_dryrun_ts) >= 60000)
                {
                  id(last_dryrun_ts) = now;
                  ESP_LOGI("DRYRUN", "Checking for Dryrun >> current: %.0f cm | last: %.0f cm", id(sensor_id).state, id(dryrun_last_dist));
                  if(id(sensor_id).state >= id(dryrun_last_dist) || isnan(id(dryrun_last_dist)))
                  {
                    ESP_LOGE("DRYRUN", "Dryrun detected, turning off pump");
                    id(oled_dryrun_page).show();
                    id(dryrun_last_dist) = id(sensor_id).state;
                    id(dryrun_state_id).publish_state(true);
                    id(pump_id).turn_off();
                    id(pump_last_reason_id).publish_state("dryrun");
                    id(mode_id).turn_off();
                  }
                  else
                  {
                    id(dryrun_last_dist) = id(sensor_id).state;
                  }
                }                
