globals:
  - id: last_sensor_ts
    type: unsigned long
    initial_value: "0"

binary_sensor:
  - platform: template
    id: sensor_state_id
    name: Sensor
    device_class: problem
    entity_category: diagnostic
sensor:
  # - platform: template
  - platform: a02yyuw
    name: "Distance"
    id: sensor_id
    uart_id: uart_id
    unit_of_measurement: cm
    accuracy_decimals: 0
    entity_category: "diagnostic"
    device_class: "distance"
    filters:
      - throttle: 1s
      - multiply: 0.1
    on_value:
      then:
        # Update the timestamp of the last valid sensor reading
        - lambda: |-
            id(last_sensor_ts) = millis();
            id(sensor_state_id).publish_state(false);
    on_value_range:
      below: $full_tank_distance
      then:
        - if:
            condition:
              - switch.is_on: pump_id
            then:
              - switch.turn_off: pump_id
              - logger.log:
                  tag: "SENSOR"
                  level: warn
                  format: "Level exceeds 100%% (Distance: %.0f cm), turning pump OFF"
                  args: [id(sensor_id).state]

  - platform: template
    id: water_level_id
    accuracy_decimals: 0
    unit_of_measurement: "%"
    update_interval: 1s
    icon: mdi:water-percent
    name: Level
    filters:
      - calibrate_linear:
          - ${full_tank_distance} -> 100.0
          - ${tank_height} -> 0.0
      - clamp:
          min_value: 0.0
          max_value: 100.0
          ignore_out_of_range: False

    lambda: |-
      if (id(sensor_id).has_state()) {
        ESP_LOGD("SENSOR", "Distance: %.0f cm | Level: %.0f%%", id(sensor_id).state, id(water_level_id).state);
        return id(sensor_id).state;
      }
      return {}; // Return NAN (Not a Number) if sensor has no state

    #   - median: # Smooth out noise
    #       window_size: 7
    #       send_every: 3
    #       send_first_at: 1

    on_value_range:
      - below: !lambda return id(start_pump_id).state;
        then:
          - if:
              condition:
                and:
                  - switch.is_on: mode_id
                  - switch.is_off: pump_id
                  - binary_sensor.is_off: sensor_state_id
                  - binary_sensor.is_off: dryrun_state_id
              then:
                - switch.turn_on: pump_id
                - text_sensor.template.publish:
                    id: pump_last_reason_id
                    state: "Auto Start"
                - logger.log:
                    tag: "water_level"
                    level: warn
                    format: "Water level below start threshold, turning pump ON."

      - above: !lambda return id(stop_pump_id).state;
        then:
          - if:
              condition:
                - switch.is_on: pump_id
              then:
                - switch.turn_off: pump_id
                - logger.log:
                    tag: "water_level"
                    level: warn
                    format: "Water level above stop threshold, turning OFF pump"
                - text_sensor.template.publish:
                    id: pump_last_reason_id
                    state: "Auto Stop"

interval:
  - interval: $sensor_check_interval
    then:
      # This lambda checks if the sensor has stopped sending data.
      # It compares the current time with the timestamp of the last received value.
      # If more than 5 seconds have passed, it assumes a sensor error.
      - lambda: |-
          unsigned long now = millis();
          if (id(last_sensor_ts) != 0 && (now - id(last_sensor_ts) > 5000))
          {
            ESP_LOGE("SENSOR", "Sensor ERROR");
            id(sensor_state_id).publish_state(true);
            id(pump_id).turn_off();
            id(pump_last_reason_id).publish_state("Sensor Error");
          }
