globals:
  - id: last_sensor_ts
    type: unsigned long
    initial_value: "0"

binary_sensor:
  - platform: template
    id: sensor_state_id
    name: Sensor
    device_class: problem
    entity_category: diagnostic

sensor:
  # - platform: template
  - platform: a02yyuw
    name: "Distance"
    id: sensor_id
    uart_id: uart_id
    unit_of_measurement: cm
    accuracy_decimals: 0
    entity_category: "diagnostic"
    device_class: "distance"
    filters:
      - throttle: 1s
      - multiply: 0.1
    on_value:
      then:
        - lambda: |-
            id(last_sensor_ts) = millis();
            id(water_level_id).publish_state(id(sensor_id).state);
            ESP_LOGD("SENSOR", "Distance: %.0f cm | Level: %.0f%%", id(sensor_id).state, id(water_level_id).state);
    on_value_range: 
      below: $full_tank_distance
      then:
        - if:
            condition:
              - switch.is_on: pump_id
            then:
              - switch.turn_off: pump_id
              - logger.log:
                  tag: "SENSOR"
                  level: warn
                  format: "Level exceeds 100%% (Distance: %.0f cm), turning pump OFF"
                  args: [id(sensor_id).state]


  - platform: template
    id: water_level_id
    accuracy_decimals: 0
    unit_of_measurement: "%"
    # update_interval: 1s
    icon: mdi:water-percent
    name: Level
    filters:
      - calibrate_linear:
        - ${full_tank_distance} -> 100.0
        - ${tank_height} -> 0.0
      - clamp:
          min_value: 0.0
          max_value: 100.0
          ignore_out_of_range: False

    #   - median: # Smooth out noise
    #       window_size: 7
    #       send_every: 3
    #       send_first_at: 1

    on_value_range:
      - below: !lambda return id(start_pump_id).state;
        then:
          - if:
              condition:
                and:
                  - switch.is_on: mode_id
                  - switch.is_off: pump_id
                  - binary_sensor.is_off: sensor_state_id
                  - binary_sensor.is_off: dryrun_state_id
              then:
                - switch.turn_on: pump_id
                - text_sensor.template.publish:
                    id: pump_last_reason_id
                    state: "Auto Start"
                - logger.log:
                    tag: "water_level"
                    level: warn
                    format: "Water level below start threshold, turning pump ON."

      - above: !lambda return id(stop_pump_id).state;
        then:
          - if:
              condition:
                - switch.is_on: pump_id
              then:
                - switch.turn_off: pump_id
                - logger.log:
                    tag: "water_level"
                    level: warn
                    format: "Water level above stop threshold, turning OFF pump"
                - text_sensor.template.publish:
                    id: pump_last_reason_id
                    state: "Auto Stop"


interval:
  - interval: $sensor_check_interval
    then:
      - lambda: |-
          unsigned long now = millis();
          if(now - id(last_sensor_ts) > 5000)
          {
            ESP_LOGE("SENSOR", "Sensor ERROR");
            id(oled_error_page).show();
            id(sensor_state_id).publish_state(true);
            id(pump_id).turn_off();
            id(pump_last_reason_id).publish_state("sensor error");
            id(last_sensor_ts) = now;
          }
          else
          {
            id(sensor_state_id).publish_state(false);
          }
      # - component.update: oled_id
      # - if:
      #     condition:
      #       or:
      #         - lambda: return isnan(id(sensor_id).state);
      #         - lambda: return id(sensor_id).state <= 0;
      #         - lambda: |-
      #             unsigned long now = millis();
      #             return (now - id(last_sensor_ts) > 5000);
      #     then:
      #       - lambda: |-
      #           id(last_sensor_ts) = millis();
      #           ESP_LOGE("SENSOR", "Sensor ERROR");
      #           id(sensor_state_id).publish_state(true);
      #       # - display.page.show: oled_error_page
      #     else:
      #       - lambda: |-
      #           id(sensor_state_id).publish_state(false);
      #           if(id(dryrun_state))
      #           {
      #             id(oled_dryrun_page).show();
      #           }
      #           else
      #           {
      #             id(oled_level_page).show();
      #           }
